### ISSUE TITLE
Introduce more secure way of generating random values (replace `os.urandom`)

### ISSUE THREAD

**Issue by Veinar** [Veinar/envcloak#2]
Goal is to improve generating of random values. I assume that package `secrets` will handle.
Steps:
* introduce new package `secrets`
* replace all occurances of `os.urandom(xxx)`

It's good first issue cause it needs small modification in code. Use Python standard package `secrets`.

**Comment by BavyaMittal** [comment]
Hello my name is Bavya and I am a software engineering student looking for a good first issue. I would like to try resolving this issue. Can I work on this if no one else is assigned yet?

**Comment by Veinar** [comment]
Hi Bavya, sure, thanks for interest in improving this package.

**Comment by Veinar** [comment]
Hi, @BavyaMittal  👋

When can I expect a solution?
If you don't want to perform it let me know.

**Comment by BavyaMittal** [comment]
Hi @Veinar! 
Sorry about the delay I am working on it and should have it ready by end of day today.

**Comment by Veinar** [comment]
Hi, @BavyaMittal 👋

Any update?

**Comment by BavyaMittal** [comment]
Hi @Veinar please see the pull request: https://github.com/Veinar/envcloak/pull/63 .
