### ISSUE TITLE
Change name of Github Actions file `test_and_build.yaml`

### ISSUE THREAD

**Issue by Veinar** [Veinar/envcloak#22]
Goal is to rename file `test_and_build.yaml` to something more approperiate because build is being executed on separate action.
Also main README.md should be updated with new name to ensure that badge is displayed correctly.

This section must be changed accordingly with new yaml name.

```md
![CI/CD Pipeline](https://github.com/Veinar/envcloak/actions/workflows/test_and_build.yaml/badge.svg)
```

**Comment by JohnnieJnr** [comment]
Hello @Veinar can I work on this issue?

**Comment by Veinar** [comment]
Hi Johnnie,

Thanks for your interest in improving `envcloak`. Clearly, I'll be pleased!
