### ISSUE TITLE
Add information about '--directory' in Examples README.md

### ISSUE THREAD

**Issue by Veinar** [Veinar/envcloak#23]
Goal is to add sections about encrypting and decrypting whole directories. Append in this file:  https://github.com/Veinar/envcloak/blob/develop/examples/cli/README.md 

Basically copy paste section about encryption and decryption but edit it to show `--directory` rather than `--input` usage. Plus mention `--force` as it is done in section about single files.  

Remember that envcloak process files in batch one by one if it encrypts/decrypts whole directories.

**Comment by JohnnieJnr** [comment]
@Veinar can I work on this issue?
