### ISSUE TITLE
Add yet another step in `test.yaml` - black formatting check.

### ISSUE THREAD

**Issue by Veinar** [Veinar/envcloak#39]
Goal is to introduce yet another step in pipeline declared in `test.yaml`  that is checking proper `black` formatting.

Command to check: 
```
black --check envcloak/
```
This command returns non zero code if code is not correctly formated and it should fail pipeline.

**Comment by Failte327** [comment]
I believe this PR addresses the changes requested, however, I haven't run the Black formatter to see what changes need to be made to the rest of the repo to make the formatter pass and therefore not fail the pipeline.

**Comment by Veinar** [comment]
Hi @Failte327 👋,

Thanks for contributing, I manually run `black` before each commit but this is rather "guardian of style" for PRs 😀.

Looks good to me, 👍
