### ISSUE TITLE
Create `--debug` or simply `--verbose` flag for CLI

### ISSUE THREAD

**Issue by Veinar** [Veinar/envcloak#8]
Add a `--verbose` or `--debug` flag to output detailed logs of actions, helpful for troubleshooting.

**Steps TODO**:

* Add flag in `cli.py` as it was done in for example `--no-gitignore`
* Pass this flag to `encryptor.py` and/or `validation.py`
* Write print statements describing operations if only flag is `True`.

🚫 **Warning:** This issue should not be implemented in parallel with #10, it may cause a conflict of interest

**Comment by ishan-coder** [comment]
Should this flag be added to all commands in cli.py?

**Comment by Veinar** [comment]
Hi @Ishan-Jadhav,

I will say frankly I trust the instinct of the one performing this task. From my perspective (I think?) yes 🤔, because every command touches the files in some way, for debugging it will be a big simplification if we know what is going on underneath. But on the other hand if `--debug`/`--verbose` will print 100 lines it will be difficult to analyse because of size of output 😂.  

You have to find a balance between `helpful` and `redundant`. ⚖️
But as I say, this is my point of view I am not imposing my vision and I am open to discussion. 👥

**Comment by Veinar** [comment]
@Ishan-Jadhav  would you like me to assign you on this?

**Comment by Ishan-Jadhav** [comment]
yes.
